version: '3'
services:
  fb-query:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fb-query
    restart: always
    # depends_on:
    #   - db
    environment:
      - PORT=2000
      - DB_TYPE=mysql
      - DB_HOST=103.67.196.23
      - DB_PORT=3306
      - DB_USER_NAME=root
      - DB_PASSWORD=Thanhtho96@1111
      - DB_DATABASE=homstay
      - NODE_OPTIONS=--max-old-space-size=4096
      - ENV=production
      - IP_SOCKET=103.67.196.23
      - PORT_SOCKET=2000
    ports:
      - '2000:2000'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge
volumes:
  redis_data:
