version: '3'
services:
  fb-query:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fb-query
    restart: always
    # depends_on:
    #   - db
    environment:
      - PORT=2000
      - DB_TYPE=mysql
      - DB_HOST=46.62.205.241
      - DB_PORT=3306
      - DB_USER_NAME=root
      - DB_PASSWORD=MyRootPass123!
      - DB_DATABASE=crawl-fb
      - NODE_OPTIONS=--max-old-space-size=4096
      - ENV=production
    ports:
      - '2000:9000'
